# Generated by Django 5.0.7 on 2024-08-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0006_soldproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='variation',
        ),
    ]
