# Generated by Django 5.0.7 on 2024-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0008_orderquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=30)),
                ('secondry_text', models.CharField(max_length=10)),
                ('banner_image', models.ImageField(upload_to='store/banners')),
            ],
        ),
        migrations.CreateModel(
            name='homeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='store/homeImage')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('second_text', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
                ('sale', models.IntegerField()),
                ('image', models.ImageField(upload_to='store/banners')),
            ],
        ),
    ]
