# Generated by Django 5.0.7 on 2024-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0009_homebanner_homeimage_salebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='StoreReview')),
                ('review', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_image',
            field=models.ImageField(upload_to='banners'),
        ),
    ]
