# Generated by Django 5.0.7 on 2024-08-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0010_storereview_alter_homebanner_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='status',
            field=models.CharField(default='rejected', max_length=50),
        ),
    ]
