# Generated by Django 5.0.7 on 2024-08-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0011_storereview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='main_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='secondry_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salebanner',
            name='second_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salebanner',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='profession',
            field=models.CharField(default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
