# Generated by Django 5.0.7 on 2024-08-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0012_alter_homebanner_main_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='button_background',
            field=models.CharField(default='#ffff'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='button_color',
            field=models.CharField(default='#ffff'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='main_text_color',
            field=models.CharField(default='#ffff'),
        ),
        migrations.AddField(
            model_name='salebanner',
            name='background',
            field=models.CharField(default='#ffff'),
        ),
        migrations.AddField(
            model_name='salebanner',
            name='main_text_color',
            field=models.CharField(default='#ffff'),
        ),
        migrations.AddField(
            model_name='salebanner',
            name='secondry_color',
            field=models.CharField(default='#ffff'),
        ),
    ]
