# Generated by Django 5.0.7 on 2024-08-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0013_homebanner_button_background_homebanner_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebanner',
            name='button_background',
            field=models.CharField(default='#ffff'),
        ),
    ]
