# Generated by Django 5.0.7 on 2024-08-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0014_salebanner_button_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='button_text',
            field=models.CharField(default='Shop Now'),
        ),
        migrations.AddField(
            model_name='salebanner',
            name='button_text',
            field=models.CharField(default='Shop Now'),
        ),
    ]
