# Generated by Django 5.0.7 on 2024-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0016_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.IntegerField(default=0),
        ),
    ]
