# Generated by Django 5.0.7 on 2024-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0017_product_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutomer_name',
            field=models.CharField(default='NO Name'),
        ),
    ]
