# Generated by Django 5.0.7 on 2024-08-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0018_order_cutomer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
