# Generated by Django 5.0.7 on 2024-08-27 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0019_rename_cutomer_name_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='orderquantity',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='VintGizmo.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VintGizmo.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VintGizmo.variation')),
            ],
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='VintGizmo.orderitem'),
        ),
    ]
