# Generated by Django 5.0.7 on 2024-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0021_brand_user_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
