# Generated by Django 5.0.7 on 2024-08-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VintGizmo', '0022_orderitem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='VintGizmo.orderitem'),
        ),
    ]
